version: "3.8"

services:
  sentence-embedder:
    container_name: sentence-embedder
    image: sentence-transformers-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8111:8000"
    volumes:
      - model-cache:/root/.cache  # сохраняет кэш модели
    restart: unless-stopped

volumes:
  model-cache:
